# Generated by Django 3.2.25 on 2026-08-02 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0005_auto_20260801_2019'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderlineitem',
            name='greeting_message',
            field=models.CharField(blank=True, help_text='Optional personalised greeting-card message', max_length=250),
        ),
    ]
