# Generated by Django 3.2.25 on 2026-08-03 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0006_orderlineitem_greeting_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='delivery_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='delivery_time',
            field=models.CharField(blank=True, choices=[('09:00-11:00', '09:00–11:00'), ('11:00-13:00', '11:00–13:00'), ('13:00-15:00', '13:00–15:00'), ('15:00-17:00', '15:00–17:00'), ('17:00-19:00', '17:00–19:00'), ('19:00-21:00', '19:00–21:00')], max_length=20, null=True),
        ),
    ]
