# Generated by Django 3.2.25 on 2026-08-06 22:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0010_alter_review_order'),
    ]

    operations = [
        migrations.RenameField(
            model_name='review',
            old_name='order',
            new_name='order_line_item',
        ),
    ]
