# Generated by Django 3.2.25 on 2026-07-31 21:09

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_auto_20260624_1525'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='extra_flower_price',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Price for each additional flower', max_digits=8, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AddField(
            model_name='product',
            name='included_flower_count',
            field=models.PositiveIntegerField(default=25, help_text='Number of flowers included in the bouquet'),
        ),
        migrations.AddField(
            model_name='product',
            name='max_extra_flowers',
            field=models.PositiveIntegerField(default=300, help_text='Maximum number of additional flowers'),
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=8),
        ),
    ]
