# Generated by Django 3.2.25 on 2026-08-02 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_auto_20260731_2309'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='allows_greeting_message',
            field=models.BooleanField(default=False, help_text='Allow customers to add a personalised message to this product'),
        ),
    ]
